# Generated by Django 5.0.6 on 2024-06-26 18:34

import django.db.models.deletion
import django.utils.timezone
import facility.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='facility',
            name='expired_date',
            field=models.DateField(default=facility.models.get_expired_date),
        ),
        migrations.AddField(
            model_name='facility',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='facility.category'),
            preserve_default=False,
        ),
    ]
