# Generated by Django 5.0.6 on 2024-07-01 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0005_remove_facility_expired_date_chosenfacility'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='chosenfacility',
            table='order',
        ),
    ]
