# Generated by Django 5.0.6 on 2024-07-01 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0006_alter_chosenfacility_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChosenFacility',
        ),
    ]
