# Generated by Django 5.0.6 on 2024-07-01 20:46

import facility.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0008_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='expired_date',
        ),
        migrations.AddField(
            model_name='facility',
            name='expired_date',
            field=models.DateField(default=facility.models.get_expired_date),
        ),
    ]
