# Generated by Django 5.0.6 on 2024-08-31 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0011_category_photo_benefit_alter_order_facilities_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
