# Generated by Django 5.0.6 on 2024-09-12 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0012_alter_category_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='facilities',
            new_name='benefits',
        ),
    ]
