# Generated by Django 5.0.6 on 2024-09-17 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0013_rename_facilities_order_benefits'),
    ]

    operations = [
        migrations.AddField(
            model_name='benefit',
            name='company',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='benefit',
            name='sub_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
