version: '3.11'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: magictap
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: RockIsdead123
    volumes:
      - postgres_data:/var/lib/postgresql/data


  web:
    build: .
    command: gunicorn mysite.wsgi:application -b 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      DATABASE_NAME: magictap
      DATABASE_USER: postgres
      DATABASE_PASSWORD: RockIsdead123
      DATABASE_HOST: db
      DATABASE_PORT: 5432
    depends_on:
      - db

volumes:
  postgres_data:
