version: '3.11'

services:
  postgres-db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: magictap
      POSTGRES_PASSWORD: magictap
      POSTGRES_DB: magictap
    ports:
      - "5432:5432"

  web:
    build: .
    command: gunicorn mysite.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - mysite/.env
    depends_on:
      - postgres-db
