version: '3.11'

services:
  magictap-postgres-db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: magictap
      POSTGRES_PASSWORD: magictap
      POSTGRES_DB: magictap
    volumes:
      - magictap_postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - mysite/.env
    depends_on:
      - magictap-postgres-db

volumes:
    magictap_postgres_data:



