# Generated by Django 5.0.6 on 2024-06-27 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
    ]
"""
Have to add here permission groups and permission for each group 
"""